from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import (
    getSampleStyleSheet
)
styles = getSampleStyleSheet()

from datetime import datetime
today = datetime.now().strftime(
    "%d %b %Y"
)

from reportlab.platypus import (
    Table,
    TableStyle
)

from reportlab.lib import colors

def export_concrete_pdf(
    project_name,
    safe_project_name,
    client_name,
    estimate_id,
    materials,
    costs,
    cement_rate,
    sand_rate,
    aggregate_rate
):
    content = []

    pdf = SimpleDocTemplate(
    f"reports/Pdf/{safe_project_name}_{estimate_id}.pdf"
)

    content.append(
    Paragraph(
    "CONCRETE ESTIMATION REPORT",
        styles["Title"]
    )
    )
     
    content.append(
    Spacer(1, 20)
    )

    content.append(
    Paragraph(
        f"Project Name: {project_name}",
        styles["Normal"]
    )
)
    content.append(
    Paragraph(
        f"Client Name: {client_name}",
        styles["Normal"]
    )
)
    content.append(
    Paragraph(
        f"Estimate ID: {estimate_id}",
        styles["Normal"]
    )
)
    content.append(
    Paragraph(
        f"Date: {today}",
        styles["Normal"]
    )
)
    content.append(
    Spacer(1, 20)
)
    
    table_data = [
    ["Material", "Quantity", "Unit", "Rate", "Amount"],

    [
        "Cement",
        materials["cement_bags"],
        "Bags",
        cement_rate,
        f'Rs. {costs["cement_cost"]}'
    ],

    [
        "Sand",
        materials["sand_m3"],
        "m³",
        sand_rate,
        f'Rs. {costs["sand_cost"]}'
    ],

    [
        "Aggregate",
        materials["aggregate_m3"],
        "m³",
        aggregate_rate,
        f'Rs. {costs["aggregate_cost"]}'
    ],
]
    
    table = Table(table_data)

    table.setStyle(
    TableStyle([
        ("GRID", (0, 0), (-1, -1), 1, colors.black),

        ("BACKGROUND",
         (0, 0),
         (-1, 0),
         colors.lightgrey),

        ("ALIGN",
         (0, 0),
         (-1, -1),
         "CENTER"),

        ("FONTNAME",
         (0, 0),
         (-1, 0),
         "Helvetica-Bold"),

         ("VALIGN",
        (0,0), (-1,-1),
         "MIDDLE"),

        ("ALIGN",
        (1,1), (-1,-1),
        "CENTER"),

        ("BOTTOMPADDING",
        (0,0), (-1,0), 10),

        ("TOPPADDING",
        (0,0), (-1,0), 10),
    ])
)
    
    content.append(table)
    content.append(
    Spacer(1, 15)
)

    content.append(
    Paragraph(
        f"Total Cost: Rs. {costs['total_cost']}",
        styles["Heading3"]
    )
)
    
    content.append(
    Spacer(1, 50)
)
    content.append(
        Paragraph(
    "Generated by CivilMate v1.1",
        styles["Normal"]
    )
)

    pdf.build(content)
    
# export_concrete_pdf(
#     "abc",
#     "abc",
#     "abc",
#     "abc",
#     "abc",
#     "abc",
#     "abc",
#     "abc",
# )